---
title: "odds_api_script"
output: html_document
---

```{r}
library(tidyverse)
library(jsonlite)
library(rvest)
library(httr)

Sys.setenv(API_KEY = "acaed33a86d9eff701cfa616e249c4e1")
```

```{r}
api_key <- Sys.getenv("API_KEY")

sports_resp <- GET(
  "https://api.the-odds-api.com/v4/sports/",
  query = list(apiKey = api_key)
)

stop_for_status(sports_resp)

sports <- fromJSON(content(sports_resp, "text", encoding = "UTF-8"))

sports |> 
  filter(grepl("NRL|Rugby League", title, ignore.case = TRUE) | grepl("rugbyleague", key, ignore.case = TRUE))
```

```{r}
api_key <- Sys.getenv("ODDS_API_KEY")

odds_resp <- GET(
  "https://api.the-odds-api.com/v4/sports/rugbyleague_nrl/odds/",
  query = list(
    apiKey = api_key,
    regions = "au",
    markets = "h2h",
    oddsFormat = "decimal",
    dateFormat = "iso"
  )
)

status_code(odds_resp)
content(odds_resp, "text", encoding = "UTF-8")
stop_for_status(odds_resp)

odds_json <- fromJSON(content(odds_resp, "text", encoding = "UTF-8"), flatten = TRUE)

headers(odds_resp)[c("x-requests-remaining","x-requests-used","x-requests-last")]
```

```{r}
odds_df <- odds_json |> 
  select(id, commence_time, home_team, away_team, bookmakers) |> 
  unnest(bookmakers) |> 
  rename(bookmaker_key = key, bookmaker_last_update = last_update) |>
  unnest(markets) |> 
  unnest(outcomes) |> 
  transmute(
    match_id = id, 
    commence_time,
    home_team,
    away_team,
    bookmaker = bookmaker_key,
    market = key, 
    outcome = name,
    odds = price,
    last_update
  ) |> 
  filter(market == "h2h") |> 
  mutate(outcome = case_when(
    outcome == home_team ~ "home_team_odds",
    outcome == away_team ~ "away_team_odds",
    T ~ NA
  )) |> 
  pivot_wider(
    names_from = outcome, values_from = odds
  )
```

```{r}
# Function

get_nrl_odds <- function(api_key) {
  
    sports_resp <- GET(
      "https://api.the-odds-api.com/v4/sports/",
      query = list(apiKey = api_key)
      )
    
    stop_for_status(sports_resp)
    
    sports <- fromJSON(content(sports_resp, "text", encoding = "UTF-8"))
    
    nrl_sport_df <- sports |> 
      filter(grepl("NRL|Rugby League", title, ignore.case = TRUE) | grepl("rugbyleague", key, ignore.case = TRUE))
  
    if(nrl_sport_df[1,]$active == FALSE){
      stop("NRL is not active: The active column contains FALSE")
    }
  
    odds_resp <- GET(
      "https://api.the-odds-api.com/v4/sports/rugbyleague_nrl/odds/",
      query = list(
        apiKey = api_key,
        regions = "au",
        markets = "h2h",
        oddsFormat = "decimal",
        dateFormat = "iso"
        )
      )
    status_code(odds_resp)
    content(odds_resp, "text", encoding = "UTF-8")
    stop_for_status(odds_resp)
    
    odds_json <- fromJSON(content(odds_resp, "text", encoding = "UTF-8"), flatten = TRUE)
    
    headers(odds_resp)[c("x-requests-remaining","x-requests-used","x-requests-last")]
    
    odds_df <- odds_json |> 
      select(id, commence_time, home_team, away_team, bookmakers) |> 
      unnest(bookmakers) |> 
      rename(bookmaker_key = key, bookmaker_last_update = last_update) |>
      unnest(markets) |> 
      unnest(outcomes) |> 
      transmute(
        id, 
        commence_time,
        home_team,
        away_team,
        bookmaker = bookmaker_key,
        market = key, 
        outcome = name,
        odds = price,
        last_update
        ) |> 
      filter(market == "h2h") |> 
      mutate(outcome = case_when(
        outcome == home_team ~ "home_team_odds",
        outcome == away_team ~ "away_team_odds",
        T ~ NA
        )) |> 
      pivot_wider(
        names_from = outcome, values_from = odds
        ) |> 
      mutate(commence_time = as_datetime(commence_time),
             last_update = as_datetime(last_update))
    
    return(odds_df)
}

get_nrl_odds(api_key = "acaed33a86d9eff701cfa616e249c4e1") |> 
    mutate(home_team = str_extract(home_team, "\\w+$"),
           away_team = str_extract(away_team, "\\w+$")) 
  
```
















