---
title: "feature_engineering_nrlR"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(nrlR)
library(tidyverse)
library(here)
library(readxl)
library(elo)

read_params <- function(){
  
  list(
    season = 2026,
    round_number = 13,
    week_start = 2,
    
    lambda = 0.94, # Degree of recency bias in rolling form variables
    elo_k = 23, # Degree of recency bias in elo model
    
    special_round = "", # "nrl-team-lists-magic-round"
    
    position_minutes_weights = tribble(
      ~position, ~w,
      "Fullback", 1,
      "Wing", 1,
      "Centre", 1,
      "Five-Eighth", 1,
      "Halfback", 1,
      "Prop", 0.6,
      "Hooker", 0.8,
      "Second Row", 0.75,
      "Lock", 0.75,
      "Interchange", 0.4
    ), # weighting stats by minutes played (approximate)
    
    comp = 12999
  )
}

params <- read_params()

historical_ladder_updated <- read_csv(here("Data/01_Raw/Ladder Data.csv"))
historical_team_updated <- read_csv(here("Data/01_Raw/Team Data.csv"))
historical_player_updated <- read_csv(here("Data/01_Raw/Player Data.csv"))
```

# Feature Engineering

```{r feature calc functions}
compute_elo <- function(df, k) {
  
  elo.run(
    result ~ team_home + team_away,
    data = df,
    k = k
  ) |> 
    as_tibble() |> 
  bind_cols(df |> select(utc_start)) |> # select date from elo input
  arrange(desc(utc_start)) |> 
  select(team_home = team.A, team_away = team.B, elo_home = elo.A, elo_away = elo.B, utc_start) |> 
  pivot_longer(
    cols = team_home:elo_away,
    names_to = c(".value", "team_location"),
    names_sep = "_"
  ) |> 
  arrange(utc_start) |> 
  group_by(team) |> 
  mutate(elo = lag(elo),
         elo = replace_na(elo, 1500)) |> 
    ungroup()
}

# input vector x, and degree of weighting for rolling forms lambda. Get lagged rolling forms output.
rolling_lambda <- function(x, lambda) {
  lag(purrr::accumulate(x, ~lambda*.x + (1-lambda)*.y), 1)
}
```

## Team Level Features

```{r team functions}
TeamContext_features <- historical_team_updated |> 
  group_by(competition_id, team_name) |> 
  arrange(team_name, utc_start) |> 
  mutate(
    days_rest = as.double(utc_start - lag(utc_start)),
    days_rest = ifelse(days_rest > 50, NA, days_rest),
    team = str_extract(team_name, "\\w+$"),
    season_stage = factor(case_when(
      round < 12 ~ "Early",
      round >= 12 & round <= 19 ~ "Mid",
      round > 19 ~ "Late"
      ), 
      levels = c("Early", "Mid", "Late"))
    ) |> 
  ungroup() |> 
  left_join(
    historical_ladder_updated, 
    by = c("team", "season", "round")
    ) |> 
  select(-team, -comp) |> 
  rename(
    ladder_points_for = points_for, 
    ladder_points_against = points_against, 
    ladder_points_diff = points_diff
    )
  
elo_input <- TeamContext_features |> 
    select(match_id, utc_start, team_name, team_location, score) |> 
    rename(team = team_name) |> 
    pivot_wider(
      id_cols = c(match_id, utc_start),
      names_from = team_location,
      values_from = c(team, score)
    ) |> 
    mutate(
      result = case_when(
      score_home > score_away ~ 1,
      score_home < score_away ~ 0,
      score_home == score_away ~ 0.5,
      T ~ 0
    )) |> 
    arrange(utc_start)

```

```{r}
elo_model <- compute_elo(elo_input, k = params$elo_k)

recent_elo_model <- compute_elo(elo_input, k = 5) |> 
  rename(shortelo = elo)

long_elo_model <- compute_elo(elo_input, k = 40) |> 
  rename(longelo = elo)
  
elo_features <- elo_input |> 
    select(utc_start, match_id, team_home, team_away) |>
    pivot_longer(
      cols = team_home:team_away,
      names_to = c(".value", "team_location"),
      names_sep = "_"
    ) |> 
    left_join(elo_model) |> 
    left_join(recent_elo_model) |> 
    left_join(long_elo_model)

elo_features %>%
  arrange(desc(utc_start))

elo_features |> 
  mutate(month = floor_date(utc_start, unit = "month")) |> 
  group_by(month) |> 
  summarise(elo = mean(elo), shortelo = mean(shortelo), longelo = mean(longelo)) |> 
  ggplot(aes(month)) +
  geom_line(aes(y = elo, colour = "red")) +
  geom_line(aes(y = shortelo, colour = "green")) +
  geom_line(aes(y = longelo, colour = "blue")) +
  scale_colour_discrete(labels = c("elo", "shortelo", "longelo"))
```

```{r}
TeamLevel_features <- TeamContext_features |> 
    left_join(
      elo_features |> 
        select(match_id, team, elo, shortelo, longelo) |> 
        rename(team_name = team), 
      by = c("match_id", "team_name")
      ) |> 
    mutate(result = score) |> 
    arrange(utc_start) |> 
    group_by(team_name) |> 
    mutate(across(
      score:goal_line_dropouts,
      ~ rolling_lambda(., params$lambda) # uses rolling forms, lagged so that future stats are not leaked
      )) |> 
    mutate(across(
      ladder_points:ladder_position, # ensures future ladder is not leaked
      ~ lag(.x, n = 1)
    )) |> 
    ungroup()

TeamLevel_features %>%
  arrange(desc(utc_start))
```

## Player Level Features

```{r player functions}

player_statistics <- historical_player_updated |> 
  unite("name", firstname:surname, sep = "_") |> # combine into one variable
  mutate(
    possessions = ifelse(possessions == 0, NA, possessions), # helps with division (per possession), immaterial to model as well
    goals_per_kick = (conversions+penalty_goals) / (conversion_attempts+penalty_goal_attempts)
    ) |> 
  select(
    -conversions, 
    -conversion_attempts, 
    -penalty_goals, 
    -penalty_goal_attempts,
    -runs_hitup,
    -runs_normal, 
    -runs_hitup_metres, 
    -runs_normal_metres, 
    -tackleds, 
    -handling_errors, 
    -post_contact_metres
    ) |> # lots of noisy stats that are similar to other stats
  left_join(
    params$position_minutes_weights, # estimate on minutes played in game based on position (not in data)
    by = "position"
    ) |> 
  mutate(
    m_per_run=run_metres/runs,
    tb_per_run=tackle_breaks/runs,
    lb_per_run=line_breaks/runs,
    offs_per_run=offloads/runs, # Attacking Runs
    
    ta_per_touch=try_assists/possessions,
    lba_per_touch=line_break_assists/possessions,
    kick_per_touch=kicks_general_play/possessions,
    pass_per_touch=passes/possessions,
    km_per_kick=ifelse(kicks_general_play ==0, NA, kick_metres/kicks_general_play), # Attacking Play-making
    
    tries_per_game=tries,
    err_per_touch=errors/possessions,
    points_per_game=points, # Attacking Overall
    
    tackles_time=tackles/w,
    saves_per_game=try_saves, # Defensive Work
    
    miss_per_t=missed_tackles/tackles,
    pen_per_t=penalties_conceded/tackles,
    ineff_per_t=tackles_ineffective/tackles # Defensive Discipline
  ) |> 
  select(-(points:penalties_conceded)) |> # We have scaled versions of these
  group_by(player_id) |> 
  arrange(player_id, utc_start) |> 
  select(
    utc_start, 
    name, 
    player_id, 
    team_name, 
    position, 
    match_id, 
    competition_id, 
    season, 
    round,
    team_location, 
    w,
    everything()
    ) |> 
  mutate(across(
    goals_per_kick:ineff_per_t,
    ~ rolling_lambda(., params$lambda) # uses rolling forms, lagged so that future stats are not leaked
    )) |> 
  ungroup()
  
PlayerLevel_features <-  player_statistics |> 
    group_by(match_id, team_name) |> 
    summarise(
      utc_start = first(utc_start),
      comp_id = first(competition_id),
      season = first(season),
      round = first(round),
      team_location = first(team_location),
      across(goals_per_kick:ineff_per_t, ~ mean(.x, na.rm = TRUE)) # Averaging statistics across team, may change to weighted averages later
      ) |> 
    ungroup()
```

## Combine Features

```{r features functions}

features_data <-  PlayerLevel_features |> 
    left_join(
      TeamLevel_features |> 
        select(-utc_start, -team_location, -competition_id, -round, -season), 
      by = c("match_id", "team_name")) |> 
    select(result, match_id, utc_start, round, season_stage, everything()) |> 
    pivot_wider(
      id_cols = c(match_id, utc_start, round, season_stage),
      names_from = team_location,
      values_from = c(result, team_name, goals_per_kick:longelo),
      names_sep = "_"
      ) |> 
    mutate(
      result = factor(case_when(
        result_home > result_away ~ "H",
        result_away > result_home ~ "A",
        T ~ "A"))
        ) |> # making target variable (binary classification)
    rename(
      date = utc_start, # clearer name
      home_team = team_name_home, 
      away_team = team_name_away,
      away_result = result_away, 
      home_result = result_home
      ) |> # cleaning names and also avoiding below function
      mutate(
      across(ends_with("_home"),
           ~ .-get(str_replace(cur_column(), "_home$", "_away")),
           .names = "{str_remove(.col,'_home$')}_diff"
           )
      ) |> # This function takes the difference between _home and _away variables, creating _diff variables.
    mutate(
      prhome = 1 / (1 + 10^( (elo_away - elo_home) / 400) ),
      shortprhome = 1 / (1 + 10^( (shortelo_away - shortelo_home) / 400) ),
      longprhome = 1 / (1 + 10^( (longelo_away - longelo_home) / 400) )
      ) |> # pr of winning based on elo ratings
    mutate(across(
      goals_per_kick_away:ladder_position_diff,
      ~ replace_na(.x, 0)
      )) |> # ok to impute this statistics like this, NAs are typically zeroes or didn't actually get the stat
    mutate(across(
      where(is.numeric),
      ~ ifelse(is.finite(.), ., NA_real_)
      )) # figure out cause of this, only 1 or 2 in a few columns

features_data %>%
  select(home_team, away_team, shortelo_home, shortelo_away, elo_home, elo_away, everything()) %>%
  arrange(desc(date))
```

```{r}
knitr::purl("feature_engineering_nrlR.Rmd", output = "feature_engineering_nrlR.R")
```












































